# Generated by Django 5.2.7 on 2025-10-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('length', models.PositiveIntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.PositiveIntegerField()),
                ('word_count', models.PositiveIntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['length'], name='analyzer_an_length_a26b5c_idx'), models.Index(fields=['word_count'], name='analyzer_an_word_co_0dc9e5_idx')],
            },
        ),
    ]
